### PR TITLE
Ensure optsConfig returns an array if unset

### LINKED ISSUE #71: v4: PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /path/to/vendor/phptek/sentry/src/Adaptor/SentryAdaptor.php on line 157
```
PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /path/to/vendor/phptek/sentry/src/Adaptor/SentryAdaptor.php on line 157
PHP Fatal error:  Uncaught TypeError: Return value of PhpTek\Sentry\Adaptor\SentryAdaptor::get_opts() must be of the type array, null returned in /path/to/vendor/phptek/sentry/src/Adaptor/SentryAdaptor.php:171
```

I have SENTRY_DSN defined in my .env and also tried inserting via Injector, but getting the above error on v4.   Rolling back to 3.0.10 resolves the issue. 

Calling dump/die of `$optsConfig` shows that it returns `null`, presumably because `private static opts`; is not defined. This will cause `array_merge` to fail

### PR DESCRIPTION
**Pull request by elliot-sawyer**
fixes #71

### CODE REVIEW

**Comment by phptek** [comment]
Legend. Thanks mate.

**Comment by phptek** [comment]
Can you make your PR against the 4.0 branch please? Then I'll tag and release 4.0.1

**Comment by elliot-sawyer** [comment]
Not sure why it's included those 3 unrelated changes from you, but I've updated it to target 4.0 branch instead

**Comment by phptek** [comment]
You'll need to rebase your feature branch against upstream 4.0 (assuming you've pulled the latest from 4.0 first)

**Comment by elliot-sawyer** [comment]
See #73

**Pull request closed without merging**
